# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXuRw3buqHWpehrKvqLGNXEtOceQHgPN
"""

pip install newspaper3k

pip install feedparser

import feedparser
from newspaper import Article

def parse_rss_feed(rss_url):
    feed = feedparser.parse(rss_url)
    article_urls = [entry.link for entry in feed.entries]
    return article_urls

def extract_article_info(article_url):
    article = Article(article_url)
    article.download()
    article.parse()

    title = article.title
    authors = article.authors
    publish_date = article.publish_date
    content = article.text

    return {
        "title": title,
        "authors": authors,
        "publish_date": publish_date,
        "content": content
    }

def process_rss_feeds(rss_urls):
    all_articles_info = []

    for rss_url in rss_urls:
        article_urls = parse_rss_feed(rss_url)

        for article_url in article_urls:
            article_info = extract_article_info(article_url)
            all_articles_info.append(article_info)

    return all_articles_info

rss_urls = [
    'https://rss.cnn.com/rss/cnn_topstories.rss',
    'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
    # Add more RSS feed URLs here
]

articles_info = process_rss_feeds(rss_urls)

for article in articles_info:
    print(f"Title: {article['title']}")
    print(f"Authors: {article['authors']}")
    print(f"Publish Date: {article['publish_date']}")
    print(f"Content: {article['content'][:200]}...")  # Print first 200 characters
    print("-" * 40)

def extract_article_info(article_url):
    try:
        article = Article(article_url)
        article.download()
        article.parse()

        title = article.title
        authors = article.authors
        publish_date = article.publish_date
        content = article.text

        return {
            "title": title,
            "authors": authors,
            "publish_date": publish_date,
            "content": content
        }
    except Exception as e:
        print(f"Error processing {article_url}: {e}")
        return None